name: CI

on: [pull_request]

jobs:
  kurtosis-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Kurtosis Tests
        uses: kurtosis-tech/kurtosis-github-action@v2
        with:
          path: "./"
          args-file: "./test_config.yml"
